# Site settings
title: DreamMr Page
baseurl: 
url: "https://github.com/DreamMr"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Wenbin Wang
  desc: Ph.D. student at Wuhan University
  email: wangwenbin97@whu.edu.cn
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance: 
  bitbucket:
  dribbble:
  flickr:
  github: DreamMr
  google_plus:
  instagram:
  keybase:
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"
  google_scholar: https://scholar.google.com/citations?hl=zh-CN&user=DSq3RSYAAAAJ

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:title
paginate_path: "/project/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
